project:
  type: website

website:
  title: "Alison Rane"
  favicon: img/favicon.png
  navbar:
    # logo: img/logoweb.png
    search: false
    pinned: true
    left:
      - href: index.qmd#toolkit
        text: Toolkit
        

format:
  html:
    css: styles.css
    theme:
      light:
        - mystyles-light.scss
      dark: 
        - mystyles-dark.scss
    mainfont: Montserrat
    toc: true



